ALTER TABLE deposits ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE deposits ALTER COLUMN amount_usd DROP NOT NULL;

ALTER TABLE deposits ADD COLUMN IF NOT EXISTS currency TEXT NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS event_id TEXT NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS origin_type TEXT NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS origin_value TEXT NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS origin_amount TEXT NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS payload JSONB NULL;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_deposits_status ON deposits (status);
CREATE INDEX IF NOT EXISTS idx_deposits_origin_value ON deposits (origin_value);
